/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type CreateRootAccountRequest struct {
	Email      string `json:"email,omitempty"`
	CustomerId int32  `json:"customerId,omitempty"`
}
