/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type VcloudOidcConfigurationDto struct {
	OrgOauthSettings       *VcloudOrgOAuthSettingsDto `json:"org_oauth_settings,omitempty"`
	ProviderConfigResponse string                     `json:"provider_config_response,omitempty"`
}
