/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type DetachAccountPolicyRequest struct {
	AccountId string   `json:"account_id,omitempty"`
	PolicyIds []string `json:"policy_ids,omitempty"`
}
