/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type BaseApiError struct {
	Code   int32                  `json:"code,omitempty"`
	Key    string                 `json:"key,omitempty"`
	Params map[string]interface{} `json:"params,omitempty"`
}
