/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type UpdateResourceTypeRequest struct {
	Value       string `json:"value,omitempty"`
	Description string `json:"description,omitempty"`
}
