/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type AttachedViaInfo struct {
	Type_        string `json:"type,omitempty"`
	ResourceName string `json:"resourceName,omitempty"`
}
