/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type AccountDto struct {
	Email    string `json:"email,omitempty"`
	Username string `json:"username,omitempty"`
}
