/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type SaveTechSupportRequest struct {
	Username  string   `json:"username,omitempty"`
	Password  string   `json:"password,omitempty"`
	DomainIds []string `json:"domain_ids,omitempty"`
}
