/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type AccountVcloudOidcResourceDto struct {
	Email     string                        `json:"email,omitempty"`
	Resources []DetailVcloudOidcResourceDto `json:"resources,omitempty"`
}
