/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type ChangePasswordTechSupportRequest struct {
	NewPassword string `json:"new_password,omitempty"`
	AccountId   string `json:"account_id,omitempty"`
}
