/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type AccountSessionGroupByDeviceDto struct {
	SessionCount int64  `json:"session_count,omitempty"`
	DeviceName   string `json:"device_name,omitempty"`
	OsName       string `json:"os_name,omitempty"`
}
