/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type LoginViaLoginPageRequest struct {
	Email        string `json:"email,omitempty"`
	Username     string `json:"username,omitempty"`
	Password     string `json:"password,omitempty"`
	DomainId     string `json:"domain_id,omitempty"`
	IsRememberMe bool   `json:"is_remember_me,omitempty"`
	UserType     string `json:"user_type,omitempty"`
}
