/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type DetachPolicyFromUserGroupRequest struct {
	UserGroupId string   `json:"user_group_id,omitempty"`
	PolicyIds   []string `json:"policy_ids,omitempty"`
}
