/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type AttachPoliciesByVttServiceRequest struct {
	AccountId     string   `json:"account_id,omitempty"`
	VttServiceIds []string `json:"vtt_service_ids,omitempty"`
}
