/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type RangeFilterString struct {
	Equals             string   `json:"equals,omitempty"`
	NotEquals          string   `json:"notEquals,omitempty"`
	Specified          bool     `json:"specified,omitempty"`
	In                 []string `json:"in,omitempty"`
	NotIn              []string `json:"notIn,omitempty"`
	GreaterThan        string   `json:"greaterThan,omitempty"`
	LessThan           string   `json:"lessThan,omitempty"`
	GreaterThanOrEqual string   `json:"greaterThanOrEqual,omitempty"`
	LessThanOrEqual    string   `json:"lessThanOrEqual,omitempty"`
	Between            string   `json:"between,omitempty"`
	NotBetween         string   `json:"notBetween,omitempty"`
}
