/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type CheckUserHasPermissionToExecuteRequest struct {
	Endpoint string `json:"endpoint,omitempty"`
	Body     string `json:"body,omitempty"`
	Method   string `json:"method,omitempty"`
}
