/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type DetailVcloudOidcResourceDto struct {
	IsOIDCConfigured bool   `json:"isOIDCConfigured,omitempty"`
	OrgName          string `json:"org_name,omitempty"`
	VdcOrgId         string `json:"vdc_org_id,omitempty"`
	PublicIp         string `json:"public_ip,omitempty"`
	HostIp           string `json:"host_ip,omitempty"`
	Domain           string `json:"domain,omitempty"`
	ServiceName      string `json:"service_name,omitempty"`
}
