/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type AttachEndpointToVttServiceRequest struct {
	EndpointId   string `json:"endpoint_id"`
	VttServiceId string `json:"vtt_service_id"`
}
