/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type SaveVttServiceRequest struct {
	Name                string                  `json:"name"`
	Description         string                  `json:"description,omitempty"`
	Url                 string                  `json:"url"`
	DefaultResourceType *DefaultResourceTypeDto `json:"default_resource_type,omitempty"`
}
