/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

import (
	"os"
)

type LocaldataUploadfileBody struct {
	VttService   **os.File `json:"vttService,omitempty"`
	Endpoint     **os.File `json:"endpoint,omitempty"`
	ResourceType **os.File `json:"resourceType,omitempty"`
	Resource     **os.File `json:"resource,omitempty"`
	Permission   **os.File `json:"permission,omitempty"`
	Policy       **os.File `json:"policy,omitempty"`
}
