/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type SavePolicyRequest struct {
	Name        string                        `json:"name"`
	Description string                        `json:"description,omitempty"`
	Type_       string                        `json:"type,omitempty"`
	Scope       string                        `json:"scope,omitempty"`
	Active      bool                          `json:"active,omitempty"`
	Permissions []PolicyResourcePermissionDto `json:"permissions,omitempty"`
}
