/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type DeleteAccountSessionRequest struct {
	ListSessionId []string `json:"listSessionId,omitempty"`
}
