/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

import (
	"time"
)

type Policy struct {
	Id          string    `json:"id,omitempty"`
	DeletedDate time.Time `json:"deletedDate,omitempty"`
	Version     int64     `json:"version,omitempty"`
	Name        string    `json:"name,omitempty"`
	Description string    `json:"description,omitempty"`
	DomainId    string    `json:"domainId,omitempty"`
	Type_       string    `json:"type,omitempty"`
	Scope       string    `json:"scope,omitempty"`
	Active      bool      `json:"active,omitempty"`
}
