/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type ListUserGroupDto struct {
	Id            string `json:"id,omitempty"`
	Name          string `json:"name"`
	Description   string `json:"description,omitempty"`
	TotalPolicies int32  `json:"total_policies,omitempty"`
	TotalAccounts int32  `json:"total_accounts,omitempty"`
}
