/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type BooleanFilter struct {
	Equals    bool   `json:"equals,omitempty"`
	NotEquals bool   `json:"notEquals,omitempty"`
	Specified bool   `json:"specified,omitempty"`
	In        []bool `json:"in,omitempty"`
	NotIn     []bool `json:"notIn,omitempty"`
}
