/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type VcloudOrgOAuthSettingsDto struct {
	OrgRedirectUri            string `json:"org_redirect_uri,omitempty"`
	IssuerId                  string `json:"issuer_id,omitempty"`
	UserAuthorizationEndpoint string `json:"user_authorization_endpoint,omitempty"`
	AccessTokenEndpoint       string `json:"access_token_endpoint,omitempty"`
	UserInfoEndpoint          string `json:"user_info_endpoint,omitempty"`
}
