/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

import (
	"time"
)

type DetailResourcesDto struct {
	Id                string                 `json:"id,omitempty"`
	Name              string                 `json:"name,omitempty"`
	Description       string                 `json:"description,omitempty"`
	ResourceType      *DetailResourceTypeDto `json:"resource_type,omitempty"`
	ServiceEndpointId string                 `json:"service_endpoint_id"`
	IsActive          bool                   `json:"is_active,omitempty"`
	LastModifiedDate  time.Time              `json:"last_modified_date,omitempty"`
}
