/*
 * VTT API
 *
 * API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iam

type SaveAccountRequest struct {
	Email                    string   `json:"email,omitempty"`
	Username                 string   `json:"username"`
	Password                 string   `json:"password,omitempty"`
	VttServiceIds            []string `json:"vtt_service_ids,omitempty"`
	PolicyIds                []string `json:"policy_ids,omitempty"`
	GroupIds                 []string `json:"group_ids,omitempty"`
	IsUsingMfa               bool     `json:"is_using_mfa,omitempty"`
	IsRequiredChangePassword bool     `json:"is_required_change_password,omitempty"`
}
