/*
 * vOKS IaC API
 *
 * This is required APIs to develop vOKS IaC
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package voks

type CreateNodeGroupRequest struct {
	CustomerId   int32            `json:"customerId,omitempty"`
	ClusterId    int32            `json:"clusterId,omitempty"`
	Name         string           `json:"name,omitempty"`
	ResourceType string           `json:"resourceType,omitempty"`
	IsAutoScale  bool             `json:"isAutoScale"`
	MinNode      int32            `json:"minNode,omitempty"`
	MaxNode      int32            `json:"maxNode,omitempty"`
	Labels       []NodeGroupLabel `json:"labels,omitempty"`
	Taints       []NodeGroupTaint `json:"taints,omitempty"`
}
