/*
 * vOKS IaC API
 *
 * This is required APIs to develop vOKS IaC
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package voks

type AddonNfsRequest struct {
	CustomerId    int32 `json:"customerId,omitempty"`
	ClusterId     int32 `json:"clusterId,omitempty"`
	AddOnsStorage int32 `json:"addOnsStorage,omitempty"`
}
