/*
 * vOKS IaC API
 *
 * This is required APIs to develop vOKS IaC
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package voks

type Addon struct {
	AddOnName   string         `json:"addOnName,omitempty"`
	Category    string         `json:"category,omitempty"`
	Description string         `json:"description,omitempty"`
	Version     []AddonVersion `json:"version,omitempty"`
}
