/*
 * vOKS IaC API
 *
 * This is required APIs to develop vOKS IaC
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package voks

type AddonUninstallRequest struct {
	CustomerId string `json:"customerId,omitempty"`
	ClusterId  int32  `json:"clusterId,omitempty"`
	Name       string `json:"name,omitempty"`
}
