/*
 * vOKS IaC API
 *
 * This is required APIs to develop vOKS IaC
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package voks

import (
	"time"
)

type Node struct {
	Name         string    `json:"name,omitempty"`
	Type_        string    `json:"type,omitempty"`
	InstanceType string    `json:"instanceType,omitempty"`
	StartTime    time.Time `json:"startTime,omitempty"`
	EndTime      time.Time `json:"endTime,omitempty"`
}
