/*
 * vOKS IaC API
 *
 * This is required APIs to develop vOKS IaC
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package voks

import (
	"time"
)

type GetDetailNfsResponse struct {
	ClusterId   int32     `json:"clusterId,omitempty"`
	Status      string    `json:"status,omitempty"`
	InternalIp  string    `json:"internalIp,omitempty"`
	MemorySize  float64   `json:"memorySize,omitempty"`
	CpuSize     float64   `json:"cpuSize,omitempty"`
	StorageSize float64   `json:"storageSize,omitempty"`
	CreatedAt   time.Time `json:"createdAt,omitempty"`
	UpdatedAt   time.Time `json:"updatedAt,omitempty"`
}
