/*
 * vOKS IaC API
 *
 * This is required APIs to develop vOKS IaC
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package voks

import (
	"time"
)

type DetailNodeGroupResponse struct {
	Id           int32            `json:"id,omitempty"`
	Name         string           `json:"name,omitempty"`
	ClusterId    int32            `json:"clusterId,omitempty"`
	Status       string           `json:"status,omitempty"`
	ResourceType string           `json:"resourceType,omitempty"`
	IsAutoScale  bool             `json:"isAutoScale,omitempty"`
	MinNode      int32            `json:"minNode,omitempty"`
	MaxNode      int32            `json:"maxNode,omitempty"`
	IsAutoRepair bool             `json:"isAutoRepair,omitempty"`
	Labels       []NodeGroupLabel `json:"labels,omitempty"`
	Taints       []NodeGroupTaint `json:"taints,omitempty"`
	CreatedAt    time.Time        `json:"createdAt,omitempty"`
	UpdatedAt    time.Time        `json:"updatedAt,omitempty"`
}
