/*
 * vOKS IaC API
 *
 * This is required APIs to develop vOKS IaC
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package voks

type VpcConfig struct {
	VpcId            int32   `json:"vpcId,omitempty"`
	VpcNetwork       string  `json:"vpcNetwork,omitempty"`
	SecurityGroupIds []int32 `json:"securityGroupIds,omitempty"`
	SubnetIds        []int32 `json:"subnetIds,omitempty"`
}
